Repository lightkurve/lightkurve, pull requests merged in 2018-12, with the labels that each got.

#375 Prevent `tpf.cadenceno` from returning zeros for TESScut TPFs
  lightkurve/targetpixelfile.py
Labels: bug, ready-for-review

#367 Expand search to TESS data products
  lightkurve/data/short_cadence_month_lookup.csv
  lightkurve/search.py
  lightkurve/tests/test_search.py
Labels: ready-for-review

#377 [bugfix] LightCurve.bin() did not bin QUALITY and CADENCENO correctly
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
Labels: bug, ready-for-review

#329 Add a "Save lightcurve" button to tpf.interact()
  lightkurve/interact.py
  lightkurve/lightcurve.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_interact.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_targetpixelfile.py
Labels: approved-to-merge
