Repository lightkurve/lightkurve, pull requests merged in 2018-10, with the labels that each got.

#273 I fixed the TESS aperture bitmask and added a TESS unit testing file
  lightkurve/targetpixelfile.py
  lightkurve/tests/data/test-tess-tpf.fits
  lightkurve/tests/test_targetpixelfile.py
Labels: ready-for-review

#287 Rename methods according to the lc.noun and lc.verb() rule
  docs/source/tutorials/1.02-target-pixel-files.ipynb
  docs/source/tutorials/1.03-what-are-lightcurves.ipynb
  docs/source/tutorials/1.04-lightcurve-files.ipynb
  docs/source/tutorials/1.05-interact-with-lightcurves-and-tpf.ipynb
  docs/source/tutorials/1.06-using-the-periodogram-class.ipynb
  docs/source/tutorials/2.01-how-to-detrend.ipynb
  docs/source/tutorials/2.02-recover-a-planet.ipynb
  docs/source/tutorials/2.03-appending-lightcurves.ipynb
  docs/source/tutorials/2.04-removing-cbvs.ipynb
  docs/source/tutorials/2.05-making-custom-apertures.ipynb
  docs/source/tutorials/2.08-making-fits-files.ipynb
  docs/source/tutorials/2.09-how-to-use-lightkurve-for-asteroseismology.ipynb
  docs/source/tutorials/2.10-how-to-make-a-supernova-lightcurve.ipynb
  docs/source/tutorials/how-to-recover-the-first-tess-candidate.ipynb
  docs/source/tutorials/quickstart.ipynb
  lightkurve/convenience.py
  lightkurve/lightcurve.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_convenience.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_periodogram.py
  lightkurve/tests/test_targetpixelfile.py
  lightkurve/utils.py
Labels: ready-for-review

#288 Add Periodogram.smooth() function
  lightkurve/periodogram.py
  lightkurve/tests/test_periodogram.py
Labels: ready-for-review

#298 Add UserWarning for time=NaN warning in LightCurve and added tests
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_utils.py
  lightkurve/utils.py
Labels: changes-requested

#244 Rework search interface
  docs/source/api/index.rst
  docs/source/api/search.rst
  lightkurve/__init__.py
  lightkurve/collections.py
  lightkurve/lightcurvefile.py
  lightkurve/search.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_collections.py
  lightkurve/tests/test_mast.py
  lightkurve/tests/test_search.py
  lightkurve/utils.py
Labels: can we merge?, ready-for-review

#306 Edit the tutorials to use `search_targetpixelfile()` and `search_lightcurvefile()` instead of `from_archive()`
  docs/source/tutorials/1.02-target-pixel-files.ipynb
  docs/source/tutorials/1.03-what-are-lightcurves.ipynb
  docs/source/tutorials/1.04-lightcurve-files.ipynb
  docs/source/tutorials/1.05-interact-with-lightcurves-and-tpf.ipynb
  docs/source/tutorials/1.06-using-the-periodogram-class.ipynb
  docs/source/tutorials/2.01-how-to-detrend.ipynb
  docs/source/tutorials/2.02-recover-a-planet.ipynb
  docs/source/tutorials/2.03-appending-lightcurves.ipynb
  docs/source/tutorials/2.04-removing-cbvs.ipynb
  docs/source/tutorials/2.05-making-custom-apertures.ipynb
  docs/source/tutorials/2.06-identify-rolling-band.ipynb
  docs/source/tutorials/2.08-making-fits-files.ipynb
  docs/source/tutorials/2.09-how-to-use-lightkurve-for-asteroseismology.ipynb
  docs/source/tutorials/2.10-how-to-make-a-supernova-lightcurve.ipynb
  docs/source/tutorials/how-to-recover-the-first-tess-candidate.ipynb
Labels: can we merge?

#308 Allow `TargetPixelFile` to be indexed and sliced
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_targetpixelfile.py
Labels: ready-for-review

#312 Better windows default
  lightkurve/correctors.py
  lightkurve/tests/test_correctors.py
Labels: can we merge?, ready-for-review

#314 Suppressed the scipy warning on lc.flatten()
  lightkurve/lightcurve.py
Labels: changes-requested
