Repository lightkurve/lightkurve, pull requests merged in 2018-11, with the labels that each got.

#320 Quick fix for test_search
  lightkurve/search.py
Labels: can we merge?, ready-for-review

#323 Increase the speed of lc.bin()
  lightkurve/lightcurve.py
Labels: approved-to-merge

#343 Fix the pandas byteorder bug
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_targetpixelfile.py
Labels: can we merge?, ready-for-review

#340 Detect filetype and provide informative warnings
  lightkurve/lightcurvefile.py
  lightkurve/search.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_utils.py
  lightkurve/utils.py
Labels: can we merge?

#344 How to install and update lightkurve with conda
  docs/source/developer.rst
  docs/source/install.rst
Labels: documentation

#347 Fix bug reported in #346
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
Labels: ready-for-review

#350 Make `utils.detect_filetype()` more robust
  lightkurve/lightcurve.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_targetpixelfile.py
  lightkurve/utils.py
Labels: can we merge?, ready-for-review

#348 Pass extra data from LightCurve to FoldedLightCurve
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
Labels: can we merge?

#352 Fixed errorbar xlabel bug (Fixes #328)
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
Labels: can we merge?

#353 lc.fold() did not set the correct `time_original`
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
Labels: can we merge?

#345 Have `tpf.create_threshold_mask()` return only one contiguous mask
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_targetpixelfile.py
Labels: can we merge?

#356 Allow quality_bitmask to be passed into open()
  lightkurve/search.py
  lightkurve/tests/test_search.py
Labels: approved-to-merge

#355 Quick fix for Bokeh v1.0.0
  lightkurve/interact.py
Labels: question

#358 Update installation instructions and developer guide in documentation; new community software, authors
  AUTHORS.rst
  docs/source/contributing.rst
  docs/source/developer.rst
  docs/source/install.rst
  docs/source/other_software.rst
Labels: documentation, ready-for-review
