Repository lightkurve/lightkurve, pull requests merged in 2019-02, with the labels that each got.

#403 Add distinct `LombScarglePeriodogram` and `BoxLeastSquaresPeriodogram` classes
  lightkurve/lightcurve.py
  lightkurve/periodogram.py
  lightkurve/tests/test_periodogram.py
Labels: approved-to-merge

#415 Introduce `CHANGES.rst` to keep track of Lightkurve changes
  CHANGES.rst
  docs/source/about/changelog.rst
  docs/source/about/developer.rst
  docs/source/about/index.rst
Labels: ready-for-review

#414 Make `SFFCorrector` robust against gaps in time
  docs/source/tutorials/02-how-to-make-a-supernova-lightcurve.ipynb
  lightkurve/correctors.py
  lightkurve/tests/test_correctors.py
Labels: ready-for-review

#420 [ColdFix] Fix for interact_bls times when using TESS data
  lightkurve/interact_bls.py
Labels: approved-to-merge

#432 Make `BoxLeastSquaresPeriodogram` robust against NaNs
  lightkurve/periodogram.py
  lightkurve/tests/test_periodogram.py
Labels: ready-for-review

#418 Return FFI cutouts with `search_tesscut`
  lightkurve/correctors.py
  lightkurve/periodogram.py
  lightkurve/search.py
  lightkurve/tests/test_periodogram.py
  lightkurve/tests/test_search.py
  requirements.txt
  setup.py
Labels: approved-to-merge

#124 sky-view:Interactive tool to show location of gaia sources on a TPF.
  lightkurve/interact.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_interact.py
  lightkurve/tests/test_targetpixelfile.py
Labels: ready-for-review

#436 Make celerite, pybind, scikit-learn, and bokeh optional dependencies
  .travis.yml
  appveyor.yml
  docs/source/about/install.rst
  docs/source/index.rst
  lightkurve/correctors.py
  lightkurve/interact.py
  lightkurve/tests/test_correctors.py
  lightkurve/tests/test_interact.py
  lightkurve/tests/test_targetpixelfile.py
  requirements.txt
  setup.py
Labels: ready-for-review

#439 Close fits files after reading header
  lightkurve/search.py
Labels: ready-for-review

#441 Support rectangular TESS FFI cutouts
  lightkurve/search.py
  lightkurve/tests/test_search.py
Labels: changes-requested

#440 Ensure all sectors are returned by `download_all()` for tesscut
  lightkurve/search.py
Labels: ready-for-review

#455 Fixed NaN plotting in tpf.plot()
  lightkurve/utils.py
Labels: ready-for-review
