Repository lightkurve/lightkurve, pull requests merged in 2019-09, with the labels that each got.

#589 Issue a warning when normalization makes no sense
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_periodogram.py
Labels: can we merge?, ready-for-review

#592 Suppress warnings during tests
  lightkurve/tests/test_interact.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_periodogram.py
  lightkurve/tests/test_search.py
Labels: work-in-progress

#596 Update stale tutorials
  docs/source/tutorials/01-lightcurve-files.ipynb
  docs/source/tutorials/01-target-pixel-files.ipynb
  docs/source/tutorials/01-what-are-lightcurves.ipynb
  docs/source/tutorials/02-how-to-make-a-supernova-lightcurve.ipynb
  docs/source/tutorials/02-how-to-recover-the-first-tess-candidate.ipynb
  docs/source/tutorials/02-recover-a-planet.ipynb
  docs/source/tutorials/03-appending-lightcurves.ipynb
  docs/source/tutorials/03-cutting-out-tpfs-from-tess-ffis.ipynb
  docs/source/tutorials/03-making-custom-apertures.ipynb
  docs/source/tutorials/03-making-fits-files.ipynb
  docs/source/tutorials/04-how-to-detrend.ipynb
  docs/source/tutorials/04-identify-rolling-band.ipynb
  docs/source/tutorials/04-interact-with-lightcurves-and-tpf.ipynb
  docs/source/tutorials/04-removing-cbvs.ipynb
  docs/source/tutorials/04-replicate-vanderburg-2014-k2sff.ipynb
  docs/source/tutorials/04-replicate-vanderburg-2014-lightkurve.ipynb
  docs/source/tutorials/README.md
Labels: ready-for-review, tutorial
