Repository lightkurve/lightkurve, pull requests merged in 2019-08, with the labels that each got.

#382 Added errorbar and scatter methods to LCF
  lightkurve/lightcurvefile.py
  lightkurve/tests/test_lightcurve.py
Labels: changes-requested

#573 add a test for dimensionless input of delta_nu
  lightkurve/seismology/core.py
  lightkurve/seismology/tests/test_butler.py
Labels: approved-to-merge

#575 Label reprs
  lightkurve/periodogram.py
  lightkurve/seismology/core.py
Labels: can we merge?
