Repository lightkurve/lightkurve, pull requests merged in 2019-04, with the labels that each got.

#485 Add a badge to run tutorials in Google Colab
  docs/source/conf.py
Labels: can we merge?

#466 Support reading-in interact-generated custom lightcurves
  lightkurve/lightcurve.py
  lightkurve/lightcurvefile.py
  lightkurve/tests/data/test_K2_interact_generated_custom-lc.fits
  lightkurve/tests/data/test_TESS_interact_generated_custom-lc.fits
  lightkurve/tests/test_lightcurve.py
  lightkurve/utils.py
Labels: can we merge?

#416 Power spectrum normalisation options
  AUTHORS.rst
  lightkurve/lightcurve.py
  lightkurve/periodogram.py
  lightkurve/tests/test_periodogram.py
Labels: enhancement

#494 [Bugfix] Use `quality_bitmask` keyword in download_all
  lightkurve/search.py
  lightkurve/tests/test_search.py
Labels: approved-to-merge, bug
