Repository lightkurve/lightkurve, pull requests merged in 2020-02, with the labels that each got.

#425 Added Odd and Even mask arrays to FoldedLightCurve
  CHANGES.rst
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
Labels: ready-for-review

#625 Added an interactive Bokeh widget to create an interactive echelle diagram.
  CHANGES.rst
  lightkurve/seismology/core.py
Labels: ready-for-review

#481 Cache TESSCut downloads to speed up file access
  CHANGES.rst
  lightkurve/search.py
  lightkurve/tests/test_search.py
Labels: easy-to-close

#682 Adding a `plot_river` method to the LightCurve Class
  docs/source/tutorials/03-using-river-plots.ipynb
  docs/source/tutorials/README.md
  docs/source/tutorials/index.rst
  lightkurve/lightcurve.py
  lightkurve/tests/test_lightcurve.py
  lightkurve/tests/test_periodogram.py
Labels: changes-requested
