Repository lightkurve/lightkurve, pull requests merged in 2020-07, with the labels that each got.

#771 New function for TPF pixel analysis: inspect_pixels()
  CHANGES.rst
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_targetpixelfile.py
Labels: feedback wanted, new-feature

#780 Add check on uniform frequency spacing to ACF2D seismology estimators (Fixed #774)
  CHANGES.rst
  lightkurve/periodogram.py
  lightkurve/seismology/core.py
  lightkurve/seismology/deltanu_estimators.py
  lightkurve/seismology/numax_estimators.py
  lightkurve/seismology/tests/test_butler.py
Labels: changes-requested

#746 Update `PLDCorrector` using `RegressionCorrector` and `DesignMatrix`
  CHANGES.rst
  lightkurve/correctors/__init__.py
  lightkurve/correctors/designmatrix.py
  lightkurve/correctors/pldcorrector.py
  lightkurve/correctors/regressioncorrector.py
  lightkurve/correctors/tesspldcorrector.py
  lightkurve/correctors/tests/test_pldcorrector.py
  lightkurve/correctors/tests/test_tesspldcorrector.py
  lightkurve/targetpixelfile.py
  lightkurve/tests/test_correctors.py
  lightkurve/tests/test_periodogram.py
  lightkurve/tests/test_synthetic_data.py
  lightkurve/tests/test_targetpixelfile.py
  setup.py
Labels: can we merge?, ready-for-review

#789 Clarify masking in `RegressionCorrector`
  lightkurve/correctors/pldcorrector.py
  lightkurve/correctors/regressioncorrector.py
Labels: ready-for-review
