Repository lightkurve/lightkurve, pull requests merged in 2022-07, with the labels that each got.

#1217 Adding ability to query `eleanor-lite` light curves to `search`
  src/lightkurve/io/__init__.py
  src/lightkurve/io/detect.py
  src/lightkurve/io/eleanorlite.py
  src/lightkurve/io/read.py
  src/lightkurve/search.py
  tests/io/test_eleanorlite.py
Labels: enhancement, approved-to-merge

#1233 Expose data product-specific doc as public API doc
  AUTHORS.rst
  CHANGES.rst
  docs/source/reference/index.rst
  docs/source/reference/io.rst
  docs/source/reference/lightcurve.rst
  src/lightkurve/io/cdips.py
  src/lightkurve/io/kepler.py
  src/lightkurve/io/pathos.py
  src/lightkurve/io/qlp.py
  src/lightkurve/io/read.py
  src/lightkurve/io/tasoc.py
  src/lightkurve/io/tess.py
Labels: approved-to-merge

#1232 Reflect TESS GI proposal url changes
  CHANGES.rst
  src/lightkurve/search.py
Labels: approved-to-merge

#1228 Fix error handling in read() / download()
  CHANGES.rst
  src/lightkurve/io/read.py
  src/lightkurve/search.py
  tests/data/test-lc-tess-pimen-100-cadences-corrupted.fits
  tests/io/test_read.py
  tests/test_search.py
Labels: approved-to-merge

#1238 Make github git blame view ignore formatting commits
  .git-blame-ignore-revs
Labels: ready-for-review

#1214 make default download_dir configurable
  CHANGES.rst
  docs/source/about/testing.rst
  docs/source/reference/config.rst
  src/lightkurve/__init__.py
  src/lightkurve/config/__init__.py
  src/lightkurve/search.py
  tests/conftest.py
  tests/test_conf.py
Labels: approved-to-merge
